# Generated by Django 5.1.2 on 2024-10-18 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('s_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('s_id', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('recurring_interval', models.CharField(default='month', max_length=10)),
                ('recurring_interval_count', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(default='recurring', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscriptions.product')),
            ],
        ),
    ]
